substitutions:
  esphome_node_name: "esp32-feather-s2"
  board_model: "lolin_s2_mini"
  framework_type: "arduino"
  ap_pass: ""
  esp_name: "Neopixel Volume"
  # KEYS
  ota_pass: "------------------------"
  encryption_key: "------------------------"
  # DISPLAY
  display_platform: "ssd1351_spi"
  display_model: "SSD1351 128x128"
  spi_clk: "10"
  spi_mosi: "11"
  pin_reset: "14"
  pin_cs: "12"
  pin_dc: "13"
  # ROTARY ENCODER
  rotaty_clk: "7"
  rotaty_a: "8"
  rotaty_b: "9" 
  num_leds: "12"
  # Title Track Artist Channel etc... Text entity media entity
  media_player2: "media_player.appletv_4k"
  # Volume Entity (can be same as media_player2)
  media_player: "media_player.bedroom_smart_tv"
  # Thermostat for HVAC mode
  climate_entity: "climate.thermostat_2"
  # optional input number helper for use with automation blueprint
  # https://github.com/kiasarecool/HA-Blueprint-thermostat-2nd-sendor---Input_number
  # set to same entity as climate_entity to not use an input_number
  # and uncomment lines in the set_things script below and comment out existing action
  input_number_entity: "input_number.target"
#######################################################
#                   end user inputs                   #
#######################################################
#       Click=Next Page - Double click=SKIP/NEXT      #
#     Short Hold <2s=Mute - Hold >2s=Toggle Screen    #
#######################################################
esphome:
  name: ${esphome_node_name}
  on_boot:
    priority: 250
    then:
      - script.execute: power_on    
time:
  - platform: homeassistant
    id: esptime
esp32:
  board: ${board_model}
  framework:
    type: ${framework_type}
logger:
api:
  encryption:
    key: "${encryption_key}"
ota:
  password: "${ota_pass}"
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "${esp_name} Hotspot"
    password: "${ap_pass}"
#######################################################
binary_sensor:
  - platform: gpio
    name: '${esp_name} Click'
    id: push_it
    pin: ${rotaty_clk}
    internal: true
    filters:      
      - delayed_off: 5ms
      - invert: 
    on_multi_click:
    - timing: 
        - ON for 10ms to 500ms     
        - OFF for at least 200ms
      then: 
        - display.page.show_next: screen
        - light.turn_off: leds
        - script.execute: rot_set_value
    - timing: 
        - ON for 400ms to 2s
      then:
        - script.execute: mute
    - timing: 
        - ON for 10ms to 300ms 
        - OFF for 10ms to 300ms     
        - ON for 10ms to 300ms
      then:
        - script.execute: skip           
    - timing: 
        - ON for at least 2.5s
      then:
        - switch.toggle: switch1
#######################################################
switch:
  - platform: template
    name: "${esp_name} Display"   
    optimistic: true
    restore_state: ON
    id: switch1
    turn_on_action:
      - lambda: id(screen).turn_on();    
    turn_off_action:
      - lambda: id(screen).turn_off();
      - light.turn_off: leds
#######################################################
script:

  - id: set_delay
    mode: restart
    then:
      - delay: 1500ms
      - script.execute: set_thing
  - id: skip
    mode: single
    then:
      - homeassistant.service:
          service: media_player.media_next_track
          data_template:                 
            entity_id: ${media_player} 
  - id: mute
    mode: single
    then:
      - homeassistant.service:
          service: media_player.volume_set
          data_template:                 
            volume_level: "0"
            entity_id: ${media_player}
      - sensor.rotary_encoder.set_value:
          id: rot_enc1
          value: "0"

  - id: power_on
    mode: single
    then:
      - light.turn_on: 
          id: leds
          brightness: 30%
          transition_length: 2s
          red: 100%
          green: 0%
          blue: 0%
      - delay: 7s
      - light.turn_on: 
          id: leds
          brightness: 40%
          transition_length: 2s
          red: 75%
          green: 37%
          blue: 100%
      - delay: 7s
      - light.turn_on: 
          id: leds
          brightness: 40%
          transition_length: 2s
          red: 0%
          green: 100%
          blue: 0%
      - delay: 10s
      - light.turn_off: 
          id: leds
          transition_length: 6s
  - id: leds_down
    mode: queued
    then:
      - light.turn_on:
          id: leds
          brightness: 0%
          effect: "none"
      - light.addressable_set:
          id: leds
          range_from: !lambda "return id(rot_enc1).state / 100 * 12;"
          range_to: 12
          color_brightness: 30%
          red: 100%
          green: 0%
          blue: 35% 
      - delay: 500ms    
      - light.turn_off: leds
  - id: leds_up
    mode: queued
    then:
      - light.turn_on:
          id: leds
          brightness: 0%
          effect: "none"
      - light.addressable_set:
          id: leds
          range_from: 0
          range_to: !lambda "return id(rot_enc1).state / 100 * 12;"
          color_brightness: 30%
          red: 30%
          green: 100%
          blue: 0%   
      - delay: 500ms    
      - light.turn_off: leds
  - id: rot_set_value
    mode: restart
    then:
      - if:
            condition:
              display.is_displaying_page:
                id: screen
                page_id: vol_page
            then:
              - sensor.rotary_encoder.set_value:
                 id: rot_enc1
                 value: !lambda "return id(media_vol).state * 100;"
      - if:
            condition:
              display.is_displaying_page:
                id: screen
                page_id: hvac_page
            then:
              - sensor.rotary_encoder.set_value:
                  id: rot_enc1
                  value: !lambda "return id(target).state * 2;" # comment out to disable input_number
#                  !lambda "return id(${climate_entity}).state * 2;"            # uncomment to disable input_number
  - id: set_thing
    mode: queued
    then:
      - if:
            condition:
              display.is_displaying_page:
                id: screen
                page_id: hvac_page
            then:
                - homeassistant.service:                                # comment out to disable input_number
                    service: input_number.set_value                     #
                    data_template:                                      #
                      value: !lambda "return id(rot_enc1).state / 2;"   #
                      entity_id: ${input_number_entity}                 # comment out to disable input_number
#            then:
#                - homeassistant.service:                                      # uncomment to disable input_number
#                    service: climate.set_temperature                          #
#                    data_template:                                            #
#                      temperature: !lambda "return id(rot_enc1).state / 2;"   #
#                      entity_id: ${climate_entity}                            # uncomment to disable input_number
      - if:
            condition:
              display.is_displaying_page:
                id: screen
                page_id: vol_page
            then:
                - homeassistant.service:
                    service: media_player.volume_set
                    data_template:                 
                      volume_level: !lambda "return id(rot_enc1).state / 100;"
                      entity_id: ${media_player} 
#######################################################
sensor:
  - platform: rotary_encoder
    name: "${esp_name} Rotary Encoder"
    id: rot_enc1
    pin_a: ${rotaty_a}
    pin_b: ${rotaty_b}
    resolution: 1
    restore_mode: RESTORE_DEFAULT_ZERO
    publish_initial_value: true
    min_value: 0
    max_value: 200
    internal: true
    on_clockwise:
      then:
        - script.execute: leds_up
        - script.execute: set_thing
    on_anticlockwise:
      then:
        - script.execute: leds_down
        - script.execute: set_thing
  - platform: homeassistant
    id: media_vol
    entity_id: ${media_player}
    attribute: volume_level
    internal: true
  - platform: homeassistant
    entity_id: ${input_number_entity}
    id: target      
  - platform: homeassistant
    entity_id: sensor.average_indoor_temperature
    id: avg_temp
#######################################################
text_sensor:
  - platform: homeassistant
    entity_id: ${media_player2}
    id: nowplay
    attribute: media_title
  - platform: homeassistant
    entity_id: ${media_player2}
    id: artist
    attribute: media_artist
  - platform: homeassistant
    entity_id: ${media_player2}
    id: app
  - platform: homeassistant
    id: hvac_txt
    entity_id: ${climate_entity}
    attribute: hvac_action
  - platform: homeassistant
    id: hvac_mode
    entity_id: ${climate_entity}
#########################################################
light:
  - platform: neopixelbus
    type: GRB
    variant: WS2812
    pin: GPIO17
    num_leds: ${num_leds}
    id: leds
    name: "${esp_name} LED Ring"
    default_transition_length: 1500ms
    restore_mode: ALWAYS_OFF
    effects:
      - addressable_scan:
      - addressable_scan:
          name: Scanner
          move_interval: 2.5s
          scan_width: 1
      - addressable_color_wipe:
      - addressable_color_wipe:
          name: Wipe           
          add_led_interval: 500ms
          reverse: false    
      - pulse:
      - pulse:
          name: "Fast Pulse"         
          transition_length: 2s
          update_interval: 1s
      - pulse:
          name: "Slow Pulse"
          id: s_pulse
          transition_length: 3s      
          update_interval: 5s
            brightness: 33%
            red: 100%
            green: 0%
            blue: 0%
      - random:
      - random:
          name: Random Colors
          transition_length: 2s
          update_interval: 4s          
      - strobe:
      - strobe:
          name: Police Strobe
          colors:
            - state: true
              brightness: 100%
              red: 100%
              green: 0%
              blue: 0%
              duration: 50ms
            - state: false
              duration: 25ms
            - state: true
              brightness: 100%
              red: 0%
              green: 0%
              blue: 100%
              duration: 50ms
            - state: false
              duration: 25ms
#######################################################
font:
  - file: 'fonts/arial.ttf'
    id: font1
    size: 18
  - file: "fonts/mdi.ttf"
    id: mdi2
    size: 15
    glyphs: [
      "\U000F075E", #Volume -
      "\U000F075D", #vol +
      ]
  - file: 'fonts/arial.ttf'
    id: font0
    size: 11
    glyphs: '^…*/|\$#<>!?"%()[]+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz&''’'
  - file: 'fonts/arial.ttf'
    id: font00
    size: 9
    glyphs: '^…*/|\$#<>!?"%()[]+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz&''’'
  - file: 'BebasNeue-Regular.ttf'
    id: font2
    size: 30
    glyphs: '^…*/|\$#<>!?"%()[]+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz&''’'
  - file: 'fonts/arial.ttf'
    id: font4
    size: 60
    glyphs: '^…*/|\$#<>!?"%()[]+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz&''’'
  - file: 'fonts/arial.ttf'
    id: font3
    size: 20
    glyphs: '^…*/|\$#<>!?"%()[]+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz&''’'
##########################################################
color:
  - id: red
    red: 100%
    green: 0%
    blue: 0%
    white: 0%
  - id: blue
    red: 0%
    green: 0%
    blue: 100%
    white: 0%
  - id: blue_green
    red: 0%
    green: 50%
    blue: 50%
    white: 5%
  - id: green
    red: 0%
    green: 100%
    blue: 0%
    white: 0%
  - id: violet
    red: 50%
    green: 0%
    blue: 50%
    white: 5%
##########################################################
spi:
  clk_pin: ${spi_clk}
  mosi_pin: ${spi_mosi}
##########################################################
display:
  - platform: ${display_platform}
    model: "${display_model}"
    id: screen
    reset_pin: ${pin_reset}
    cs_pin: ${pin_cs}
    dc_pin: ${pin_dc}
    update_interval: 0.1s 
    brightness: 95%
    pages:
      - id: vol_page
        lambda: |-
          it.rectangle(0, 0, 128, 128, id(blue));
          it.filled_rectangle(14, 3, id(rot_enc1).state, 18, id(blue));
          it.rectangle(13, 2, 102, 20, id(violet));
          if (id(app).has_state()) {
          it.printf(64, 40, id(font3), id(blue), TextAlign::BASELINE_CENTER, "%s", id(app).state.c_str());
          } else {
          it.print(64, 40, id(font3), id(violet), TextAlign::BASELINE_CENTER, "Volume");
          }
          it.strftime(64, 55, id(font0), id(green), TextAlign::BASELINE_CENTER, "%H:%M", id(esptime).now());
          it.print(2, 18, id(mdi2), id(red), "\U000F075E");
          it.print(115, 18, id(mdi2), id(green), "\U000F075D");
          it.printf(64, 70, id(font0), id(green), TextAlign::BASELINE_CENTER, "%s", id(nowplay).state.c_str());
          it.printf(64, 99, id(font2), id(violet), TextAlign::BASELINE_CENTER, "%.0f%", id(rot_enc1).state);
          it.printf(64, 123, id(font00), id(blue), TextAlign::BASELINE_CENTER, "%s", id(artist).state.c_str());
          it.line(0, 110, 128, 110, id(blue));
      - id: hvac_page
        lambda: |-
          it.rectangle(0, 0, 128, 128, id(blue));
          it.filled_rectangle(54, 3, ((id(target).state - 60) * 2), 18, id(blue));
          it.rectangle(53, 2, 40, 20, id(violet));
          it.printf(70, 60, id(font2), id(green), TextAlign::BASELINE_LEFT, "%.1f°", id(avg_temp).state);
          it.print(75, 60, id(font0), id(blue_green), "Average");
          it.printf(3, 60, id(font2), id(green), TextAlign::BASELINE_LEFT, "%.1f°", id(target).state);
          it.printf(8, 60, id(font0), id(blue_green), "Target");
          it.printf(2, 0, id(font2), id(blue), TextAlign::BASELINE_CENTER, "%s -%s",id(hvac_mode).state.c_str(), id(hvac_txt).state.c_str());



